/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useContext, useEffect, useLayoutEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { AnimationContext } from "@/app/contexts/AnimationContext";

export function MatheusV3(props: any) {
  const group = useRef();
  const { animationKey, updateLoader } = useContext(AnimationContext)

  // @ts-ignore
  const { nodes, materials, animations } = useGLTF("/3dModels/MatheusBoneco.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.register('/sw.js')
        .then(registration => {
          console.log('Service Worker registered with scope:', registration.scope);
        })
        .catch(error => {
          console.error('Service Worker registration failed:', error);
        });
    }
  }, []);

  useEffect(() => {
    if (actions[animationKey]) {
      // Parar todas as animações atuais
      Object.values(actions).forEach((action) => {
        if (action?.isRunning()) {
          action?.stop();
        }
      });

      // Reproduzir a animação selecionada
      const selectedAction = actions[animationKey];
      selectedAction?.play();
    } else {
      console.warn(`Ação de animação '${animationKey}' não encontrada.`);
    }

    // if (animationKey !== 'HappyIdle') {
    //   setTimeout(() => {
    //     updateAnimationKey('HappyIdle')

    //     clearTimeout(0)
    //   }, 5000)
    // }
    updateLoader(false)
  }, [actions, animationKey]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature001">
          <skinnedMesh
            name="EyeLeft001"
            geometry={nodes.EyeLeft001.geometry}
            material={materials.OLHOORIGINAL}
            skeleton={nodes.EyeLeft001.skeleton}
            morphTargetDictionary={nodes.EyeLeft001.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeLeft001.morphTargetInfluences}
          />
          <skinnedMesh
            name="EyeRight001"
            geometry={nodes.EyeRight001.geometry}
            material={materials.OLHOORIGINAL}
            skeleton={nodes.EyeRight001.skeleton}
            morphTargetDictionary={nodes.EyeRight001.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeRight001.morphTargetInfluences}
          />
          <skinnedMesh
            name="Wolf3D_Body001"
            geometry={nodes.Wolf3D_Body001.geometry}
            material={materials.PELE}
            skeleton={nodes.Wolf3D_Body001.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Body001.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Body001.morphTargetInfluences}
          />
          <skinnedMesh
            name="Wolf3D_Glasses001"
            geometry={nodes.Wolf3D_Glasses001.geometry}
            material={materials.OCULOS}
            skeleton={nodes.Wolf3D_Glasses001.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Hair001"
            geometry={nodes.Wolf3D_Hair001.geometry}
            material={materials.CABELO}
            skeleton={nodes.Wolf3D_Hair001.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Head001"
            geometry={nodes.Wolf3D_Head001.geometry}
            material={materials.CABEÇA}
            skeleton={nodes.Wolf3D_Head001.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Head001.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Head001.morphTargetInfluences}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Bottom001"
            geometry={nodes.Wolf3D_Outfit_Bottom001.geometry}
            material={materials.CALÇA}
            skeleton={nodes.Wolf3D_Outfit_Bottom001.skeleton}
            morphTargetDictionary={
              nodes.Wolf3D_Outfit_Bottom001.morphTargetDictionary
            }
            morphTargetInfluences={
              nodes.Wolf3D_Outfit_Bottom001.morphTargetInfluences
            }
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Footwear001"
            geometry={nodes.Wolf3D_Outfit_Footwear001.geometry}
            material={materials.TENIS}
            skeleton={nodes.Wolf3D_Outfit_Footwear001.skeleton}
            morphTargetDictionary={
              nodes.Wolf3D_Outfit_Footwear001.morphTargetDictionary
            }
            morphTargetInfluences={
              nodes.Wolf3D_Outfit_Footwear001.morphTargetInfluences
            }
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Top001"
            geometry={nodes.Wolf3D_Outfit_Top001.geometry}
            material={materials.CASACO}
            skeleton={nodes.Wolf3D_Outfit_Top001.skeleton}
            morphTargetDictionary={
              nodes.Wolf3D_Outfit_Top001.morphTargetDictionary
            }
            morphTargetInfluences={
              nodes.Wolf3D_Outfit_Top001.morphTargetInfluences
            }
          />
          <skinnedMesh
            name="Wolf3D_Teeth001"
            geometry={nodes.Wolf3D_Teeth001.geometry}
            material={materials.BOCA}
            skeleton={nodes.Wolf3D_Teeth001.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Teeth001.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Teeth001.morphTargetInfluences}
          />
          <primitive object={nodes.Hips} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/3dModels/MatheusBoneco.glb");
