"use client"
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useContext, useEffect, useLayoutEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { AnimationContext } from "@/app/contexts/AnimationContext";

export function MatheusV2(props: any) {
  const { animationKey } = useContext(AnimationContext)

  const group = useRef();
  // @ts-ignore
  const { nodes, materials, animations } = useGLTF("/3dModels/matheussincero.glb");
  const { actions } = useAnimations(animations, group);

  // console.log(actions)

  useEffect(() => {
    if (actions[animationKey]) {
      // Parar todas as animações atuais
      Object.values(actions).forEach((action) => {
        if (action?.isRunning()) {
          action?.stop();
        }
      });

      // Reproduzir a animação selecionada
      const selectedAction = actions[animationKey];
      selectedAction?.play();
    } else {
      console.warn(`Ação de animação '${animationKey}' não encontrada.`);
    }
  }, [actions, animationKey]);

  useLayoutEffect(() => {
    if (typeof window !== "undefined") {
      const sw = window?.navigator?.serviceWorker

      if (sw) {
        sw.register("/sw.js", { scope: "/" }).then((registration) => {
          console.log("Service Worker registration successful with scope: ", registration.scope);
        }).catch((err) => {
          console.log("Service Worker registration failed: ", err);
        });
      }
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature001">
          <skinnedMesh
            name="EyeLeft001"
            geometry={nodes.EyeLeft001.geometry}
            material={materials["Wolf3D_Eye.005"]}
            skeleton={nodes.EyeLeft001.skeleton}
            morphTargetDictionary={nodes.EyeLeft001.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeLeft001.morphTargetInfluences}
          />
          <skinnedMesh
            name="EyeRight001"
            geometry={nodes.EyeRight001.geometry}
            material={materials["Wolf3D_Eye.005"]}
            skeleton={nodes.EyeRight001.skeleton}
            morphTargetDictionary={nodes.EyeRight001.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeRight001.morphTargetInfluences}
          />
          <skinnedMesh
            name="Wolf3D_Body001"
            geometry={nodes.Wolf3D_Body001.geometry}
            material={materials["Wolf3D_Body.005"]}
            skeleton={nodes.Wolf3D_Body001.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Body001.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Body001.morphTargetInfluences}
          />
          <skinnedMesh
            name="Wolf3D_Glasses001"
            geometry={nodes.Wolf3D_Glasses001.geometry}
            material={materials["Wolf3D_Glasses.005"]}
            skeleton={nodes.Wolf3D_Glasses001.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Head001"
            geometry={nodes.Wolf3D_Head001.geometry}
            material={materials["Wolf3D_Skin.005"]}
            skeleton={nodes.Wolf3D_Head001.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Head001.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Head001.morphTargetInfluences}
          />
          <skinnedMesh
            name="Wolf3D_Headwear001"
            geometry={nodes.Wolf3D_Headwear001.geometry}
            material={materials["Wolf3D_Headwear.005"]}
            skeleton={nodes.Wolf3D_Headwear001.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Bottom001"
            geometry={nodes.Wolf3D_Outfit_Bottom001.geometry}
            material={materials["Wolf3D_Outfit_Bottom.005"]}
            skeleton={nodes.Wolf3D_Outfit_Bottom001.skeleton}
            morphTargetDictionary={
              nodes.Wolf3D_Outfit_Bottom001.morphTargetDictionary
            }
            morphTargetInfluences={
              nodes.Wolf3D_Outfit_Bottom001.morphTargetInfluences
            }
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Footwear001"
            geometry={nodes.Wolf3D_Outfit_Footwear001.geometry}
            material={materials["Wolf3D_Outfit_Footwear.005"]}
            skeleton={nodes.Wolf3D_Outfit_Footwear001.skeleton}
            morphTargetDictionary={
              nodes.Wolf3D_Outfit_Footwear001.morphTargetDictionary
            }
            morphTargetInfluences={
              nodes.Wolf3D_Outfit_Footwear001.morphTargetInfluences
            }
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Top001"
            geometry={nodes.Wolf3D_Outfit_Top001.geometry}
            material={materials["Wolf3D_Outfit_Top.005"]}
            skeleton={nodes.Wolf3D_Outfit_Top001.skeleton}
            morphTargetDictionary={
              nodes.Wolf3D_Outfit_Top001.morphTargetDictionary
            }
            morphTargetInfluences={
              nodes.Wolf3D_Outfit_Top001.morphTargetInfluences
            }
          />
          <skinnedMesh
            name="Wolf3D_Teeth001"
            geometry={nodes.Wolf3D_Teeth001.geometry}
            material={materials["Wolf3D_Teeth.005"]}
            skeleton={nodes.Wolf3D_Teeth001.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Teeth001.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Teeth001.morphTargetInfluences}
          />
          <primitive object={nodes.Hips} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/3dModels/matheussincero.glb");